---
  - name: Create admin group
    group: "name={{admingroup}}"

  - name: Add admin group to sudoers
    lineinfile: dest=/etc/sudoers state=present regexp='^%admin ALL\=' line='%admin ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'
    register: admingroupsudoers

  - name: Remove wheel group in sudoers if admin group was added
    lineinfile: dest=/etc/sudoers state=absent regexp="^%wheel" validate='visudo -cf %s'
    when: admingroupsudoers.changed

  - name: Create admin users
    user: "name={{item.name}} uid={{item.uid}} group={{item.groups}} shell={{item.shell}}"
    with_items: adminusers

  - name: Add ssh keys to admin users
    authorized_key: user="{{item.name}}" key="{{ lookup('file', 'files/' + item.name + '.pub') }}"
    with_items: adminusers
