---
  - name: Test login in as current/configured user
    local_action: shell ssh {{ ssh_extra_args }} {{ inventory_hostname }} whoami
    ignore_errors: true
    always_run: true
    changed_when: login_as_self.rc is not defined
    register: login_as_self

  - name: Use root to login
    set_fact: remote_user="root" should_become=false
    always_run: true
    failed_when: login_as_self.rc is not defined
    when: login_as_self.rc != 0

  - name: Use current/configured user to log in
    set_fact: remote_user="{{ login_as_self.stdout_lines[0] }}" should_become=true
    always_run: true
    failed_when: login_as_self.rc is not defined
    when: login_as_self.rc == 0

  # Run the rest as remote_user
  - block:
    - name: Gather facts, we know the username now
      setup:

    - name: Create admin group
      group: "name={{admingroup}}"
      register: reg_add_admin_group

    - name: Create groups from a list
      group: 
        name: "{{item.name}}"
        gid: "{{item.gid | default(omit)}}"
      register: reg_add_group
      when: admin_list_of_groups is defined and admin_list_of_groups.0 is defined
      with_items: "{{ admin_list_of_groups }}"

    - name: Install Python SE Linux support (needed on CentOS7 with Enforcing)
      package: name=libselinux-python state=present
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= 7

    - name: Create sudoers file for admin group
      copy: dest=/etc/sudoers.d/{{ admingroup }} owner=root group=root mode=0440
            content='%{{ admingroup }} ALL=(ALL) NOPASSWD:ALL'
            validate='visudo -cf %s'
      register: reg_add_sudoers_file_admins
      when: admin_sudoers

    - name: Ensure /etc/sudoers.d is scanned by sudo
      lineinfile: dest=/etc/sudoers regexp="#includedir\s+/etc/sudoers.d" line="#includedir /etc/sudoers.d"
      when: admin_sudoers

    - name: Add or remove users from the adminusers and moreusers lists
      user:
        name: "{{item.name}}"
        state: "{{item.state | default('present')}}"
        uid: "{{item.uid | default(omit) }}"
        group: "{{item.group | default(omit) }}"
        groups: "{{item.groups | default(omit) }}"
        shell: "{{item.shell | default('/bin/bash')}}"
        comment: "{{item.comment | default(omit)}}"
        remove: "{{item.remove | default(omit)}}"
      with_items: 
       - "{{ adminusers | default([]) }}"
       - "{{ moreusers | default([]) }}"

    - name: Remove wheel group in sudoers if admin group was added and the sudoers.d file for the admin group was added
      lineinfile:
        dest: /etc/sudoers
        state: absent 
        regexp: "^%wheel"
        validate: 'visudo -cf %s'
      when: reg_add_admin_group.changed and reg_add_sudoers_file_admins.changed and admin_sudoers

      # No password. Required for sshd PasswordAuthentication no
    - name: Remove passwords from present adminusers and moreusers if adminremove_passwords is True
      user:
        name: "{{item.name}}"
        password: '*'
        state: "{{item.state | default('present')}}"
        uid: "{{item.uid | default(omit) }}"
        group: "{{item.group | default(omit) }}"
        groups: "{{item.groups | default(omit) }}"
        shell: "{{item.shell | default('/bin/bash')}}"
        comment: "{{item.comment | default(omit)}}"
        remove: "{{item.remove | default(omit)}}"
      with_items: 
       - "{{ adminusers | default([]) }}"
       - "{{ moreusers | default([]) }}"
      when: adminremove_passwords and item.state == 'present'

    - name: Add ssh keys and use key_options if option is used
      authorized_key: user="{{item.name}}" key='{{item.pubkey}}' key_options='{{ item.options | default(omit) }}'
      when: item.state == 'present' and item.pubkey is defined
      with_items: 
       - "{{ adminusers | default([]) }}"
       - "{{ moreusers | default([]) }}"

    - name: Add or remove ssh keys to root user
      authorized_key: 
        user: "root" 
        key: '{{item.pubkey}}'
        state: "{{item.state | default('present')}}"
      when: item.pubkey is defined
      with_items: "{{ admin_root_keys | default([]) }}"

    # end of block
    remote_user: "{{ remote_user }}"
    become: "{{ should_become }}"
