---
  - name: Create admin group
    group: "name={{admingroup}}"
    register: reg_add_admin_group

  - name: Create sudoers file for admin group
    copy: dest=/etc/sudoers.d/{{ admingroup }} owner=root group=root mode=0600
          content='%{{ admingroup }} ALL=(ALL) NOPASSWD:ALL'
          validate='visudo -cf %s'
    register: reg_add_sudoers_file_admins
    when: admin_sudoers

  - name: Ensure /etc/sudoers.d is scanned by sudo
    lineinfile: dest=/etc/sudoers regexp="#includedir\s+/etc/sudoers.d" line="#includedir /etc/sudoers.d"
    when: admin_sudoers

  - name: Add or remove admin users
    user: >
      name={{item.name}}
      state={{item.state | default('present')}}
      uid={{item.uid}}
      group={{item.groups}}
      shell={{item.shell | default('/bin/bash')}}
    with_items: adminusers

  - name: Remove wheel group in sudoers if admin group was added and the sudoers.d file for the admin group was added
    lineinfile: dest=/etc/sudoers state=absent regexp="^%wheel" validate='visudo -cf %s'
    when: reg_add_admin_group.changed and reg_add_sudoers_file_admins.changed and admin_sudoers

    # No password. Required for sshd PasswordAuthentication no
  - name: Remove passwords from admins if remove_passwords is true
    user: >
      name={{item.name}}
      password='*'
    with_items: adminusers
    when: adminremove_passwords

  - name: Add ssh keys to admin users
    authorized_key: user="{{item.name}}" key="{{item.pubkey}}"
    when: item.state == 'present' and item.pubkey is defined
    with_items: adminusers
